### ISSUE TITLE
wordpress 各主题如何嵌入 for [wordpress]

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/StackHub#103]
**What type of your feature request?**  

## Wordpress enable theme steps:

1. copy theme and plugins to correct directory
2. modify wp-includes/default-constants.php
   ```
	if ( !defined('WP_DEFAULT_THEME') )
		define( 'WP_DEFAULT_THEME', '{{wordpress_theme_meta[wordpress_theme].theme}}' );
   ```

Note

```
# theme: https://libs.websoft9.com/apps/wordpress/avada/avada.zip
# plugin: https://libs.websoft9.com/apps/wordpress/avada/fusion-core.zip
# plugin lists

```
#商业主题的下载包包含官方源码和主题
#注意：当无插件下载的时，请写：plugin: "" or plugin: False
wordpress_theme_meta:

  avada: 
    theme: "avada"
    plugin:
      - fusion-core
      - fusion-builder
      - LayerSlider
      - revslider
      
  porto: 
    theme: "porto"
    plugin:
      - Ultimate_VC_Addons
      - dynamic-featured-image
      - js_composer
      - porto-functionality
      - revslider
      - sliderrevolution
      - wpbakerybuilder

  the7: 
    theme: "dt-the7"
    plugin:
      - Ultimate_VC_Addons
      - dt-the7-core
      - go_pricing
      - js_composer
      - revslider
    
  divi: 
    theme: "Divi"
    plugin: 
      - Divi-Builder-Layouts-147
```

Ansible code
```
- block:
  - name: Download {{wordpress_theme}} theme
    unarchive:
      src: "{{wordpress_theme_download_url}}/{{wordpress_theme}}/{{wordpress_theme_meta[wordpress_theme].theme}}.zip"
      dest: /data/wwwroot/wordpress/wp-content/themes
      remote_src: yes

  - name: Download  plugin
    unarchive:
      src: "{{wordpress_theme_download_url}}/{{wordpress_theme}}/{{item}}.zip"
      dest: /data/wwwroot/wordpress/wp-content/plugins
      remote_src: yes
    with_items:
      - "{{wordpress_theme_meta[wordpress_theme].plugin}}"
    when: wordpress_theme_meta[wordpress_theme].plugin !=""

  - name: Replace theme name in the file default-constants.php
    template:
      src: default-constants.php
      dest: /data/wwwroot/wordpress/wp-includes/default-constants.php
      mode: 0640
  when: wordpress_theme != ""
```

**Comment by qiaofeng1227** [comment]
wp-cli问题：
使用ansible项目模板的本地：wp-cli.phar
```
[29-Nov-2022 02:02:00 UTC] PHP Fatal error:  Uncaught PharException: phar "/usr/local/bin/wp" has a broken signature in /usr/local/bin/wp:3
Stack trace:
#0 /usr/local/bin/wp(3): Phar::mapPhar()
#1 {main}
  thrown in /usr/local/bin/wp on line 3
```

使用在线下载方式解决：
refer to: https://github.com/wp-cli/wp-cli

**Comment by qiaofeng1227** [comment]
```
# image,docs: https://hub.docker.com/_/wordpress/

version: '3.8'

services:

  wordpress:
    image: wordpress:latest
    container_name: $APP_NAME
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: 10m
    ports:
      - $APP_HTTP_PORT:80
    environment:
      WORDPRESS_DB_HOST: $APP_NAME-db
      WORDPRESS_DB_USER: $DB_MYSQL_USER
      WORDPRESS_DB_PASSWORD: $DB_MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $DB_MYSQL_NAME
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress:/var/www/html
      - ./src/php_exra.ini:/usr/local/etc/php/conf.d/php_exra.ini

  mysql:
    image: mariadb:$DB_MYSQL_VERSION
    container_name: $APP_NAME-db
    restart: unless-stopped
    ports:
     - ${DB_MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $DB_MYSQL_NAME
      MYSQL_USER: $DB_MYSQL_USER
      MYSQL_PASSWORD: $DB_MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_MYSQL_PASSWORD

  cli:
    image: wordpress:cli
    container_name: $APP_NAME-cli
    restart: unless-stopped
    command: sh -c "sleep 20 && wp core install --path=/var/www/html --url=localhost --title=test --admin_user=test --admin_password=test --admin_email=test@example.com"
    volumes:
      - wordpress:/var/www/html
   

volumes:
  wordpress:
  mysql_data:
    
networks:
  default:
    name: $APP_NETWORK
    external: true
```
