### ISSUE TITLE
ghost on 腾讯云无法启动容器 for ￥100

### ISSUE THREAD

**Issue by LalicNine** [Websoft9/StackHub#126]
screenshot：
![%CV0CJFIE 7EH_E47F{03~J](https://user-images.githubusercontent.com/109707255/211145527-e28e92ab-00d8-49dd-940b-f3d3e7eaa3c4.png)

**Comment by zl-go** [comment]
docker-compose.yml文件中没有指定env_file，加上即可
```
services:
  ghost:
    image: ghost:$APP_VERSION
    container_name: $APP_NAME
    restart: unless-stopped
    ports:
      - $APP_HTTP_PORT:2368
    env_file: .env
```
