### ISSUE TITLE
优化容器日志方案

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/StackHub#86]
**What type of your feature request?**  

- [ ] Add new features
- [ ] Improve current features

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Additional context**

**Comment by chendelin1982** [comment]
以 WordPress 为例，它的日志位置为：
```
docker inspect --format='{{.LogPath}}' CONTAINER_NAME
```

然后 echo ""  到上述位置即可

**Comment by chendelin1982** [comment]
也可以往 docker-compose 文件增加：
```
  wordpress:
    image: wordpress:${APP_VERSION}
    container_name: ${APP_NAME}
    restart: always
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: 10m
```
